In [2]:
import tensorflow as tf

print("--- Bài 1 ---")
b1 = tf.zeros([2, 3])
print(b1)

print("\n--- Bài 2 ---")
X = tf.constant([[1, 2, 3], [4, 5, 6]])
b2 = tf.zeros_like(X)
print(b2)

print("\n--- Bài 3 ---")
b3 = tf.fill([3, 2], 5)
print(b3)

print("\n--- Bài 4 ---")
# Khởi tạo tập hợp chứa các số chẵn trong [5, 10]
even_pool = tf.constant([6, 8, 10])
# Lấy ngẫu nhiên 50 giá trị từ mảng even_pool (index từ 0 đến 2)
indices = tf.random.uniform([50], minval=0, maxval=3, dtype=tf.int32)
b4 = tf.gather(even_pool, indices)
print(b4)

print("\n--- Bài 5 ---")
# Bắt đầu từ 10, kết thúc trước 102, bước nhảy là 2
b5 = tf.range(10, 102, 2)
print(b5)

print("\n--- Bài 6 ---")
b6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print(b6)

print("\n--- Bài 7 ---")
b7 = tf.random.uniform([3, 2], minval=0.0, maxval=2.0)
print(b7)
print("--- Bài 8 ---")
X8 = tf.constant([[1, 2], [3, 4], [5, 6]])
b8 = tf.random.shuffle(X8)
print("Sau khi shuffle:\n", b8.numpy())

print("\n--- Bài 9 ---")
t9 = tf.random.normal([10, 10, 3])
b9 = tf.image.random_crop(t9, size=[5, 5, 3])
print("Shape sau khi random_crop:", b9.shape)

print("\n--- Bài 10 ---")
x10 = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)
y10 = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)
# Dùng hàm tf.where để xử lý logic điều kiện if-else
b10 = tf.where(x10 < y10, x10 + y10, tf.where(x10 > y10, x10 - y10, x10))
print("x:  ", x10.numpy())
print("y:  ", y10.numpy())
print("Kq: ", b10.numpy())

print("\n--- Bài 11 ---")
x11 = tf.random.uniform([3, 2], minval=5, maxval=10)
y11 = tf.random.uniform([2, 3], minval=15, maxval=20)
diag_x = tf.linalg.diag_part(x11)
# Chuyển vị y thành kích thước (3, 2) để thực hiện được phép cộng element-wise
x_plus_y = x11 + tf.transpose(y11)
print("Đường chéo của x: ", diag_x.numpy())
print("x + y (transpose):\n", x_plus_y.numpy())
print("--- Bài 12 ---")
x12 = tf.random.normal([3, 2, 2])
y12 = tf.random.normal([3, 2, 2])

# Đưa tính toán lên Graph bằng Decorator @tf.function
@tf.function
def compute_ops(x, y):
    return x + y, x - y, x * y, x / y

add, sub, mul, div = compute_ops(x12, y12)
print("Tính toán trên graph hoàn tất, shape trả về của phép cộng:", add.shape)

print("\n--- Bài 13 & Bài 14 ---")
class MathModel(tf.Module):
    @tf.function
    def sum_tensors(self, x, y):
        return x + y

    @tf.function
    def diff_and_prod_tensors(self, x, y):
        return x - y, x * y

math_model = MathModel()
print("Tổng (ví dụ 10 + 5):", math_model.sum_tensors(10, 5).numpy())

print("\n--- Bài 15 & Bài 16 ---")
class GeometryModel(tf.Module):
    @tf.function
    def chu_vi_hcn(self, a, b):
        return (a + b) * 2

    @tf.function
    def dt_toan_phan_hhcn(self, a, b, c):
        s_xq = (a + b) * c * 2
        s_tp = (a * b) * 2 + s_xq
        return s_tp

geo_model = GeometryModel()
print("Chu vi HCN (a=4, b=5):", geo_model.chu_vi_hcn(4, 5).numpy())
print("S Toàn phần HHCN (a=3, b=4, c=5):", geo_model.dt_toan_phan_hhcn(3, 4, 5).numpy())

print("\n--- Bài 17, 18 & Bài 19 ---")
class LogicProofModel(tf.Module):
    @tf.function
    def chung_minh_hinh_thang_song_song(self, AD, BC, AB, CD):
        # AD // BC <=> AD = BC và AB = CD
        return tf.logical_and(tf.equal(AD, BC), tf.equal(AB, CD))

    @tf.function
    def chung_minh_day_hinh_thang_bang_nhau(self, AD, BC, is_AD_parallel_BC):
        # AB = CD <=> AD = BC và AD // BC
        return tf.logical_and(tf.equal(AD, BC), is_AD_parallel_BC)

    @tf.function
    def chung_minh_duong_trung_binh(self, is_MN_parallel_BC, MN, BC, MB):
        # Điều kiện MN là trung bình: MN // BC và MN = BC/2
        dk_trung_binh = tf.logical_and(is_MN_parallel_BC, tf.equal(MN, BC / 2))
        logic_step = tf.logical_and(tf.equal(MN, MB), is_MN_parallel_BC)
        return tf.logical_and(dk_trung_binh, logic_step)

proof_model = LogicProofModel()
print("Khởi tạo thành công ProofModel cho việc kiểm tra logic bài 17, 18, 19.")


--- Bài 1 ---
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

--- Bài 2 ---
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)

--- Bài 3 ---
tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)

--- Bài 4 ---
tf.Tensor(
[10  6 10  8  6 10  8  6 10  8 10  6 10 10 10  6  6  8 10  6  8 10  6  8
 10  8  6  6  8  8  8  8  6  6  8  8 10 10  6  6 10 10  6 10  8  6  8 10
 10  6], shape=(50,), dtype=int32)

--- Bài 5 ---
tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)

--- Bài 6 ---
tf.Tensor(
[[-0.01060411 -1.1937741 ]
 [-4.1289763   0.52032316]
 [ 0.21302915  1.9351437 ]], shape=(3, 2), dtype=float32)

--- Bài 7 ---
tf.Tensor(
[[0.34390473 1.2155287 ]
 [0.32468033 1.8949885 ]
 [1.8033428  1.44595   ]], shape=(3, 2), dtype=float32)
--- Bài 8 ---
Sau khi shuffle:
 [[5 6]
 [1 2]
 [3 4]]