In [41]:
import numpy as np
import pandas as pd
# Bài 1: Tạo mảng 3x3 ngẫu nhiên từ [0, 20] và kiểm tra tất cả phần tử khác 0
print("Bài 1")
arr1=np.random.randint(0, 21, size=(3,3))
print("Mảng 3x3 vừa tạo:\n ",arr1)
all_non_zero=np.all(arr1 !=0)
print("Tất cả các phần tử đều khác 0?:",all_non_zero)
# Bài 2: Tạo mảng 3x3 ngẫu nhiên từ [0, 20] và kiểm tra ít nhất 1 phần tử khác 0
print("Bài 2")
arr2=np.random.randint(0,21, size=(3,3))
print("Mảng 3x3 vừa tạo:\n",arr2)
any_non_zero=np.any(arr2!=0)
print("Tồn tại ít nhất một phần tử khác 0?:",any_non_zero)
# Bài 3: Sử dụng np.greater, np.greater_equal, np.less, np.less_equal
print("Bài 3")
#So sánh 2 mảng 1 chiều
a_1d=np.array([2, 5, 9, 12])
b_1d=np.array([4, 5, 8, 15])
print("Mảng 1D a:",a_1d)
print("Mảng 1D b:",b_1d)
print("a>b(geater):",np.greater(a_1d,b_1d))
print("a>=b(greater_equal):",np.greater_equal(a_1d,b_1d))
#So sánh 2 mảng 2 chiều
a_2d=np.array([[1,2],[8,6]])
b_2d=np.array([[4,5],[7,3]])
print("Mảng 2D a:\n",a_2d)
print("Mảng 2D b:\n",b_2d)
print("a<b(less):\n",np.less(a_2d,b_2d))
print("a<=b(less_equal):\n",np.less_equal(a_2d,b_2d))
#Bài 4: Tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
print("Bài 4")
ones_arr=np.ones(10)
zeros_arr=np.zeros(10)
fives_arr=np.full(10,5)
arr4=np.concatenate((ones_arr,zeros_arr,fives_arr))
print("Mảng gồm 10 số 1, 10 số 0 và 10 số 5:\n",arr4)
#Bài 5: Tạo mảng số nguyên chẵn từ [30, 70]
print("Bài 5")
arr5=np.arange(30, 72, 2)
print("Mảng số nguyên chẵn từ 30 đến 70:\n",arr5)
#Bài 6: Tạo ma trận đơn vị 3x3 bằng hàm indentity
arr6=np.identity(3)
print("Ma trận đơn vị 3x3:\n",arr6)
#Bài 7: Tạo mảng 10 phần tử trong khoảng [15, 55]
print("Bài 7")
arr7=np.random.randint(15,56,10)
print("Mảng ban đầu",arr7)
print("Mảng sau khi bỏ phần tử đầu và cuối:",arr7[1:-1])
#Bài 8: Tạo mảng 20 phần từ trong [0,20], đổi dấu các số trong khoảng [9, 15]
print("Bài 8")
arr8= np.random.randint(10, 21, 20)
print("Mảng ban đầu:\n",arr8)
arr8[(arr8>=9)&(arr8<=15)]*=-1
print("Mảng sau khi đổi dấu các số thuộc [9,15]:\n",arr8)
#Bài 9: Tạo ma trận 3x4, mỗi phần tử có giá trị [10, 21]
print("Bài 9")
arr9=np.random.randint(10,22,size=(3,4))
print("Ma trận 3x4:\n",arr9)
#Bài 10: Tạo ma trận 1x10, biên là 1, bên trong các phần tử có giá trị là 0
print ("Bài 10")
arr10=np.zeros((1,10))
arr10[0,0]=1
arr10[0,-1]=1
print("Ma trận 1x10:\n",arr10)
#Bài 11: Tạo ma trận 5x5 có đường chéo chính là 1, 2, 3, 4, 5
print("Bài 11")
arr11=np.diag([1,2,3,4,5])
print("Ma trận 5x5:\n",arr11)
#Bài 12: Tạo mảng 3x3x3 và tính tổng theo mỗi dòng, mỗi cột
print("Bài 12")
arr12=np.random.randint(1,10, size=(3,3,3))
print("Mảng 3x3x3:\n",arr12)
sum_dong=np.sum(arr12,axis=1)
sum_cot=np.sum(arr12,axis=2)
print("Tổng theo mỗi dòng:\n",sum_dong)
print("Tổng theo mỗi cột:\n",sum_cot)
#Bài 13: 2 vector ngẫu nhiên 10 phần tử, tính inner product (np.dot)
vec1=np.random.randint(1, 10, 10)
vec2=np.random.randint(1, 10, 10)
print("Vector 1:",vec1)
print("Vector 2:",vec2)
inner_product=np.dot(vec1,vec2)
print("Tích vô hướng Inner product:",inner_product)
#Bài 14: Ma trận A(4x3), vector y(3) Thêm vector y vào từng dòng của A
print("Bài 14")
A=np.random.randint(1,10,size=(4,3))
y=np.random.randint(1,10,3)
print ("Ma trận A (4x3):\n",A)
print ("Vector y (3 phần tử):",y)
result_14= A+7
print("Ma trận sa khi cộng y vào từng dòng:\n", result_14)
#Bài 15: Cộng trừ nhân chia 2 Series Pandas
print ("Bài 15")
s1=pd.Series([2,4,6,8,10])
s2=pd.Series([1,3,5,7,10])
print("Cộng 2 Series:\n",s1+s2)
print("\nTrừ 2 Series:\n",s1-s2)
print("\nNhân 2 Series:\n",s1*s2)
print("\nChia 2 Series:\n",s1/s2)
#Bài 16: Chuyển đổi cột đầu tiên thành Series
print ("Bài 16")
df16=pd.DataFrame({'col1':[1,2,3,4,7,11],'col2':[4,5,6,9,5,0],'col3':[7,5,8,12,1,11]})
print("DataFrame ban đầu:\n",df16)
#Bài 17: Sắp xêp theo cột của DataFrame 4x3 ngẫu nhiên
print ("Bài 17")
df17=pd.DataFrame(np.random.randint(1,50,size=(4,3)),columns=['Col1','Col2','Col3'])
print("DataFrame ban đầu:\n",df17)
df17_sorted=df17.sort_values(by='Col1')
print("DataFrame sau khi sắp xếp:\n",df17_sorted)
#Bài 18: Thay đổi index của một Series
print ("Bài 18")
s18=pd.Series([1,2,3,4,5],index=['A','B','C','D','E'])
print("Series ban đầu:\n",s18)
s18_reindexed=s18.reindex(['B','A','C','D','E'])
print("Series sau khi thay đổi index:\n",s18_reindexed)
#Bài 19: Tìm phần tử trong Series x mà không có trong Series y
print ("Bài 19")
sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])
print("Series 1:\n",sr1)
print("Series 2:\n",sr2)
result_19=sr1[~sr1.isin(sr2)]
print("Kết quả:\n",result_19)
#Bài 20: Phép toàn numpy.union1d, numpy.intersect1d trên 2 Series ngẫu nhiên 20 phần tử
print ("Bài 20")
x20=pd.Series(np.random.randint(1,30,20))
y20=pd.Series(np.random.randint(1,30,20))
union_xy=np.union1d(x20,y20)
intersect_xy=np.intersect1d(x20,y20)
print("Phép toàn numpy.union1d:\n",union_xy)
print("Phép toàn numpy.intersect1d:\n",intersect_xy)
#Bài 21: Thêm series y vào series x theo chiều dọc và chiều ngang
print ("Bài 21")
x21=pd.Series([1,2,3,4,5])
y21=pd.Series(['p','q','r','w','y'])
vertical_concat=pd.concat([x21,y21],axis=0)
horizontal_concat=pd.concat([x21,y21],axis=1)
print("Kết quả theo chiều dọc:\n",vertical_concat)
print("Kết quả theo chiều ngang:\n",horizontal_concat)
#Bài 22: Tạo hiển thị dữ liệu Dataframe từ dictionary
print("Bài 22")
excam_data={
    'name':['Anastasia','Dima','Katherine','James','Emily','Michael','Matthew','Laura','Kevin','Jonas'],
    'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
    'attempts':[1,3,2,3,2,3,1,1,2,1],
    'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']
}
labels=['a','b','c','d','e','f','g','h','i','j']
df22=pd.DataFrame(excam_data,index=labels)
print("DataFrame vừa tạo:\n")
print(df22)
#Bài 23: Cho biết 3 dòng đầu tiên
print("Bài 23")
print("3 dòng đầu tiên:\n",df22.head(3))
#Bài 24: Chọn cột 'name' và 'score'
print("Bài 24")
print("Cột name:\n",df22['name'])
print("Cột score:\n",df22['score'])
#Bài 25: Chọn những dòng có attemps >2
print("Bài 25")
print("Dòng có attempts >2:\n",df22[df22['attempts']>2])
#Bài 26: Cho biết số dòng, số cột của DataFrame
print("Bài 26")
print("Số dòng của DataFrame:",df22.shape[0])
print("Số cột của DataFrame:",df22.shape[1])
#Bài 27: Cho biết những dòng có score là NaN
print("Bài 27")
print("Dòng có score là NaN:\n",df22[df22['score'].isnull()])
#Bài 28: Cho biết những dòng có score trong khoảng (15, 20)
print("Bài 28")
print("Dòng có score trong khoảng (15, 20):\n",df22[(df22['score']>=15)&(df22['score']<=20)])
#Bài 29: Những dòng có attempt > 2 và score trong khoảng (15, 20)
print("Bài 29")
print("Dòng có attempt > 2 và score trong khoảng (15, 20):\n",df22[(df22['attempts']>2)&(df22['score']>=15)&(df22['score']<=20)])
#Bài 30: Thay đổi giá trị dòng 'd', cột score là 19 ( sử dụng loc)
print("Bài 30")
df22.loc['d','score']=19
print("DataFrame sau khi thay đổi:\n",df22)

Bài 1
Mảng 3x3 vừa tạo:
  [[ 4 12  0]
 [ 1  0  0]
 [16 19  3]]
Tất cả các phần tử đều khác 0?: False
Bài 2
Mảng 3x3 vừa tạo:
 [[19  8 13]
 [16  8 14]
 [ 8 15  8]]
Tồn tại ít nhất một phần tử khác 0?: True
Bài 3
Mảng 1D a: [ 2  5  9 12]
Mảng 1D b: [ 4  5  8 15]
a>b(geater): [False False  True False]
a>=b(greater_equal): [False  True  True False]
Mảng 2D a:
 [[1 2]
 [8 6]]
Mảng 2D b:
 [[4 5]
 [7 3]]
a<b(less):
 [[ True  True]
 [False False]]
a<=b(less_equal):
 [[ True  True]
 [False False]]
Bài 4
Mảng gồm 10 số 1, 10 số 0 và 10 số 5:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]
Bài 5
Mảng số nguyên chẵn từ 30 đến 70:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Bài 7
Mảng ban đầu [30 46 26 27 27 44 44 43 26 35]
Mảng sau khi bỏ phần tử đầu và cuối: [46 26 27 27 44 44 43 26]
Bài 8
Mảng ban đầu:
 [18 12 19 17 11 20 17 20 10 17 14 15 18 20 12 19 17 11 19 18]
Mảng sa